flowchart TD
    B1 -- fa:fa-code-fork New Fork --> A3
    C3 -- fa:fa-code-pull-request Pull Request to Develop --> A2
    B2 -- fa:fa-code Continue Development --> A2
    D2 -- fa:fa-bug Work in Beta --> C2
    F2 -- fa:fa-bug Fix Bugs & Minor Changes --> E2
    B5 --> F5
    F2 --> A4
    A1 --> B4
    G2 --> A4
    A4 --> B1
    B4 --> B1
    B1 --> A6
    subgraph main[fa:fa-github Main Branch]
        A1[fa:fa-clock Stable Version] --> B1[fa:fa-clock Last Version of Main]
    end
    subgraph Develop[fa:fa-code-fork Develop Branch]
       A2[fa:fa-code Dev Works into the Code] --> B2[fa:fa-gears Alpha version] -- Finish Development --> C2[fa:fa-gears Beta version] --> D2[fa:fa-bug Debug and fix errors] -- Fixed all Bugs & Errors --> E2[fa:fa-gears Gamma version] --> F2[fa:fa-vial Testing] -- Finish Testing --> G2[fa:fa-gem Gold version - Release Candidate] --> H1[fa:fa-flag-checkered Finsh & Prepare the Pull Request] -- fa:fa-code-pull-request Pull Request to Main ---> A1
    end
    subgraph fork[fa:fa-github Dev Fork]
       A3[fa:fa-code Dev Works into the Code] --> B3[fa:fa-gears Test changes] --> C3[fa:fa-flag-checkered Finsh & Prepare the Pull Request]
    end
    subgraph releases[fa:fa-clock Releases]
        A4[fa:fa-clock Pre-Release]
        B4[fa:fa-clock Release]
    end
    subgraph pull_request[fa:fa-code-pull-request Pull Request Process]
        A5[fa:fa-magnifying-glass Review Changes] --> B5[fa:fa-message Discussions] --> C5[fa:fa-circle-check Pull Request Approved & Changes Included] --> D5[fa:fa-rectangle-xmark Close Pull Request] --> E5[fa:fa-code-merge Merge Branch]
        F5[fa:fa-circle-xmark Pull Request Denied & Suggested solution] --> G5[fa:fa-rectangle-xmark Close Pull Request] --> H5[fa:fa-bug Fix errors] --> I5[fa:fa-code-pull-request New Pull Request]
    end
    subgraph remote_server[fa:fa-terminal Remote Server]
        A6[fa:fa-terminal-git-alt Git Client] --> B6[fa:fa-terminal Remote Server] --> C6[fa:fa-users End User]
    end